"""rename address

Revision ID: 560547b4072b
Revises: f920d9978ab4
Create Date: 2024-11-11 17:35:30.886410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560547b4072b'
down_revision = 'f920d9978ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
