"""add Department

Revision ID: 978cc735234b
Revises: 6bccf9050fe2
Create Date: 2024-11-11 17:23:01.181123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978cc735234b'
down_revision = '6bccf9050fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
